services:
  app:
    image: "${APP_IMAGE?err}"
    restart: on-failure
    command: sh -c "alembic upgrade head && gunicorn"
    ports:
      - "${FLASK_PORT?err}"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - portfolio

networks:
  portfolio:
    driver: bridge