name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
#      - name: Setup Qemu
#        uses: docker/setup-qemu-action@v1

      - name: Setup Docker buildX
        uses: docker/setup-buildx-action@v1

      - name: Build the docker image
        run: |
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
